# -*- coding: utf-8 -*-
from odoo import api, SUPERUSER_ID

MODULE = "sid_stock_actions_ov"

# (model, id, xml_name)
RECORDS = [
  [
    "ir.actions.server",
    998,
    "server_cancelar_stock_move_mad_out_23_01316_998"
  ],
  [
    "ir.actions.server",
    669,
    "server_ov_actividades_albaran_669"
  ],
  [
    "ir.actions.server",
    1188,
    "server_ov_actividades_hereda_1188"
  ],
  [
    "ir.actions.server",
    1187,
    "server_ov_actividades_hereda_1187"
  ],
  [
    "ir.actions.server",
    1186,
    "server_ov_actividades_hereda_1186"
  ],
  [
    "ir.actions.server",
    1185,
    "server_ov_actividades_hereda_1185"
  ],
  [
    "ir.actions.server",
    1184,
    "server_ov_actividades_hereda_1184"
  ],
  [
    "ir.actions.server",
    1183,
    "server_ov_actividades_hereda_1183"
  ],
  [
    "ir.actions.server",
    1182,
    "server_ov_actividades_hereda_1182"
  ],
  [
    "ir.actions.server",
    1181,
    "server_ov_actividades_hereda_1181"
  ],
  [
    "ir.actions.server",
    1180,
    "server_ov_actividades_hereda_1180"
  ],
  [
    "ir.actions.server",
    1179,
    "server_ov_actividades_hereda_1179"
  ],
  [
    "ir.actions.server",
    1178,
    "server_ov_actividades_hereda_1178"
  ],
  [
    "ir.actions.server",
    1207,
    "server_ov_actividades_hereda_1207"
  ],
  [
    "ir.actions.server",
    1190,
    "server_ov_actividades_hereda_1190"
  ],
  [
    "ir.actions.server",
    1189,
    "server_ov_actividades_hereda_1189"
  ],
  [
    "ir.actions.server",
    1220,
    "server_ov_actividades_a_linea_albaran_1220"
  ],
  [
    "ir.actions.server",
    1204,
    "server_ov_actividades_a_linea_albaran_1204"
  ],
  [
    "ir.actions.server",
    1423,
    "server_ov_actualiza_certificados_1423"
  ],
  [
    "ir.actions.server",
    1397,
    "server_ov_actualiza_certificado_transfer_hecha_1397"
  ],
  [
    "ir.actions.server",
    1659,
    "server_ov_actualiza_demanda_stock_move_line_1659"
  ],
  [
    "ir.actions.server",
    1020,
    "server_ov_actualizar_cantidad_sin_precio_prohibido_1020"
  ],
  [
    "ir.actions.server",
    1027,
    "server_ov_albaran_en_chatter_1027"
  ],
  [
    "ir.actions.server",
    1616,
    "server_ov_albaran_sin_contacto_1616"
  ],
  [
    "ir.actions.server",
    1347,
    "server_ov_arreglo_movimientos_de_existencias_1347"
  ],
  [
    "ir.actions.server",
    1326,
    "server_ov_arreglo_movimientos_de_existencias_1326"
  ],
  [
    "ir.actions.server",
    1130,
    "server_ov_arreglo_movimientos_de_existencias_1130"
  ],
  [
    "ir.actions.server",
    1545,
    "server_ov_asigna_cert_id_1545"
  ],
  [
    "ir.actions.server",
    1494,
    "server_ov_asigna_todo_el_grupo_de_abastecimiento_1494"
  ],
  [
    "ir.actions.server",
    1469,
    "server_ov_asignar_certificate_id_1469"
  ],
  [
    "ir.actions.server",
    1599,
    "server_ov_cert_cv_de_rutas_cv_1599"
  ],
  [
    "ir.actions.server",
    1416,
    "server_ov_cert_certificados_1416"
  ],
  [
    "ir.actions.server",
    1400,
    "server_ov_cert_certificados_1400"
  ],
  [
    "ir.actions.server",
    1502,
    "server_ov_cancel_1502"
  ],
  [
    "ir.actions.server",
    1253,
    "server_ov_cancela_movimientos_de_producto_1253"
  ],
  [
    "ir.actions.server",
    1527,
    "server_ov_cert_iguala_a_cantidad_hecha_1527"
  ],
  [
    "ir.actions.server",
    1218,
    "server_ov_certificados_aviso_a_luis_1218"
  ],
  [
    "ir.actions.server",
    1198,
    "server_ov_certificados_aviso_a_luis_1198"
  ],
  [
    "ir.actions.server",
    1219,
    "server_ov_certificados_aviso_a_luis_1219"
  ],
  [
    "ir.actions.server",
    1402,
    "server_ov_certificados_obligatorios_recepciones_1402"
  ],
  [
    "ir.actions.server",
    1414,
    "server_ov_certificados_obligatorios_recepciones_1414"
  ],
  [
    "ir.actions.server",
    1477,
    "server_ov_certificados_obligatorios_recepciones_1477"
  ],
  [
    "ir.actions.server",
    1404,
    "server_ov_certificados_obligatorios_recepciones_1404"
  ],
  [
    "ir.actions.server",
    1443,
    "server_ov_certificados_solo_en_movimientos_de_certificado_1443"
  ],
  [
    "ir.actions.server",
    790,
    "server_ov_coladas_negativas_no_permitidas_790"
  ],
  [
    "ir.actions.server",
    1604,
    "server_ov_coladas_negativas_no_permitidas_1604"
  ],
  [
    "ir.actions.server",
    1439,
    "server_ov_control_pdf_certificados_1439"
  ],
  [
    "ir.actions.server",
    1399,
    "server_ov_crear_certificados_1_para_todos_1399"
  ],
  [
    "ir.actions.server",
    1398,
    "server_ov_crear_certificados_1_para_todos_1398"
  ],
  [
    "ir.actions.server",
    1463,
    "server_ov_cuentas_analiticas_1463"
  ],
  [
    "ir.actions.server",
    1505,
    "server_ov_ds_asigna_cert_1505"
  ],
  [
    "ir.actions.server",
    1481,
    "server_ov_david_responsable_al_confirmar_in_o_cert_ptllo_1481"
  ],
  [
    "ir.actions.server",
    684,
    "server_ov_descripcion_genericos_albaran_684"
  ],
  [
    "ir.actions.server",
    979,
    "server_ov_descripcion_en_picking_979"
  ],
  [
    "ir.actions.server",
    697,
    "server_ov_descripcion_en_picking_697"
  ],
  [
    "ir.actions.server",
    977,
    "server_ov_descripcion_en_picking_977"
  ],
  [
    "ir.actions.server",
    1412,
    "server_ov_devoluciones_1412"
  ],
  [
    "ir.actions.server",
    1411,
    "server_ov_devoluciones_1411"
  ],
  [
    "ir.actions.server",
    955,
    "server_ov_dropship_contacto_sidsa_955"
  ],
  [
    "ir.actions.server",
    961,
    "server_ov_dropship_contacto_sidsa_961"
  ],
  [
    "ir.actions.server",
    743,
    "server_ov_email_al_confirmar_albaranes_743"
  ],
  [
    "ir.actions.server",
    1039,
    "server_ov_email_al_confirmar_albaranes_1039"
  ],
  [
    "ir.actions.server",
    1418,
    "server_ov_encontrar_certificados_por_linea_1418"
  ],
  [
    "ir.actions.server",
    1547,
    "server_ov_estado_pick_y_out_1547"
  ],
  [
    "ir.actions.server",
    1244,
    "server_ov_evitar_lotes_sin_uom_1244"
  ],
  [
    "ir.actions.server",
    679,
    "server_ov_fecha_recepcion_y_prevista_679"
  ],
  [
    "ir.actions.server",
    1663,
    "server_ov_forzar_consignee_en_picking_1663"
  ],
  [
    "ir.actions.server",
    788,
    "server_ov_hoy_788"
  ],
  [
    "ir.actions.server",
    787,
    "server_ov_hoy_787"
  ],
  [
    "ir.actions.server",
    1386,
    "server_ov_imprime_hoja_picking_1386"
  ],
  [
    "ir.actions.server",
    1498,
    "server_ov_imprime_y_deja_adjunto_1498"
  ],
  [
    "ir.actions.server",
    1603,
    "server_ov_informacion_coladas_no_disponibles_1603"
  ],
  [
    "ir.actions.server",
    1032,
    "server_ov_informacion_coladas_no_disponibles_1032"
  ],
  [
    "ir.actions.server",
    1605,
    "server_ov_informacion_coladas_no_disponibles_1605"
  ],
  [
    "ir.actions.server",
    1549,
    "server_ov_limita_lotes_no_de_recepcion_1549"
  ],
  [
    "ir.actions.server",
    791,
    "server_ov_limite_cantidad_colada_791"
  ],
  [
    "ir.actions.server",
    949,
    "server_ov_limite_cantidad_colada_949"
  ],
  [
    "ir.actions.server",
    1360,
    "server_ov_lotes_sc_sin_colada_prohibir_1360"
  ],
  [
    "ir.actions.server",
    1444,
    "server_ov_mensaje_devoluciones_compra_1444"
  ],
  [
    "ir.actions.server",
    1462,
    "server_ov_mensaje_facturacion_in_1462"
  ],
  [
    "ir.actions.server",
    1440,
    "server_ov_mensaje_facturacion_out_1440"
  ],
  [
    "ir.actions.server",
    1272,
    "server_ov_movimientos_posteriores_1272"
  ],
  [
    "ir.actions.server",
    1271,
    "server_ov_movimientos_posteriores_1271"
  ],
  [
    "ir.actions.server",
    1526,
    "server_ov_multi_descripcion_desde_venta_1526"
  ],
  [
    "ir.actions.server",
    1672,
    "server_ov_multi_descripcion_desde_venta_1672"
  ],
  [
    "ir.actions.server",
    1525,
    "server_ov_multi_descripcion_desde_venta_1525"
  ],
  [
    "ir.actions.server",
    671,
    "server_ov_notas_albaran_671"
  ],
  [
    "ir.actions.server",
    1359,
    "server_ov_no_sc_s_c_sin_colada_1359"
  ],
  [
    "ir.actions.server",
    1499,
    "server_ov_partner_consignee_nulo_1499"
  ],
  [
    "ir.actions.server",
    1026,
    "server_ov_pasar_de_cancelado_a_borrador_1026"
  ],
  [
    "ir.actions.server",
    1594,
    "server_ov_prueba_coladas_1594"
  ],
  [
    "ir.actions.server",
    1370,
    "server_ov_regenera_movimientos_original_y_destino_1370"
  ],
  [
    "ir.actions.server",
    1371,
    "server_ov_regenera_movimientos_original_y_destino_1371"
  ],
  [
    "ir.actions.server",
    1369,
    "server_ov_regenera_original_y_destino_1369"
  ],
  [
    "ir.actions.server",
    1655,
    "server_ov_registro_informe_noi_1655"
  ],
  [
    "ir.actions.server",
    1460,
    "server_ov_reposicion_1460"
  ],
  [
    "ir.actions.server",
    1264,
    "server_ov_retorno_solo_se_pueden_validar_si_la_cantidad_facturada_de_compra_es_menor_que_la_entregada_1264"
  ],
  [
    "ir.actions.server",
    1263,
    "server_ov_retorno_solo_se_pueden_validar_si_la_cantidad_facturada_es_menor_que_la_entregada_1263"
  ],
  [
    "ir.actions.server",
    1276,
    "server_ov_scrap_a_borrador_1276"
  ],
  [
    "ir.actions.server",
    1200,
    "server_ov_tag_sale_activities_en_lineas_de_venta_1200"
  ],
  [
    "ir.actions.server",
    1669,
    "server_ov_toggle_x_enviar_pdf_albaran_a_chatter_1669"
  ],
  [
    "ir.actions.server",
    944,
    "server_ov_transportista_944"
  ],
  [
    "ir.actions.server",
    1067,
    "server_ov_transportista_1067"
  ],
  [
    "ir.actions.server",
    1259,
    "server_ov_cancela_mov_de_prod_1259"
  ],
  [
    "ir.actions.server",
    1257,
    "server_ov_cancela_mov_de_prod_1257"
  ],
  [
    "ir.actions.server",
    1255,
    "server_ov_cancela_mov_de_prod_1255"
  ],
  [
    "ir.actions.server",
    1479,
    "server_ov_david_1479"
  ],
  [
    "ir.actions.server",
    1670,
    "server_ov_hecho_mov_de_prod_1670"
  ],
  [
    "ir.actions.act_window",
    1091,
    "act_window_asignacion_1091"
  ],
  [
    "ir.actions.act_window",
    1095,
    "act_window_asignacion_por_linea_1095"
  ],
  [
    "ir.actions.act_window",
    1262,
    "act_window_entregas_madrid_1262"
  ],
  [
    "ir.actions.act_window",
    1129,
    "act_window_entregas_madrid_1129"
  ],
  [
    "ir.actions.act_window",
    1094,
    "act_window_entregas_madrid_1094"
  ],
  [
    "ir.actions.act_window",
    1092,
    "act_window_entregas_madrid_1092"
  ],
  [
    "ir.actions.act_window",
    1324,
    "act_window_stock_on_hand_1324"
  ],
  [
    "ir.actions.act_window",
    544,
    "act_window_inventory_overview_544"
  ],
  [
    "ir.actions.act_window",
    543,
    "act_window_product_moves_543"
  ],
  [
    "ir.actions.act_window",
    558,
    "act_window_stock_moves_558"
  ],
  [
    "ir.actions.act_window",
    1228,
    "act_window_stock_moves_1228"
  ],
  [
    "base.automation",
    49,
    "automation_ov_email_al_confirmar_albaranes_49"
  ],
  [
    "base.automation",
    57,
    "automation_ov_limite_cantidad_colada_57"
  ],
  [
    "base.automation",
    77,
    "automation_ov_dropship_contacto_sidsa_77"
  ],
  [
    "base.automation",
    236,
    "automation_ov_cert_cv_de_rutas_cv_236"
  ],
  [
    "base.automation",
    82,
    "automation_ov_dropship_contacto_sidsa_82"
  ],
  [
    "base.automation",
    93,
    "automation_ov_descripcion_en_picking_93"
  ],
  [
    "base.automation",
    94,
    "automation_ov_descripcion_en_picking_94"
  ],
  [
    "base.automation",
    106,
    "automation_ov_actualizar_cantidad_sin_precio_prohibido_106"
  ],
  [
    "base.automation",
    198,
    "automation_ov_no_sc_s_c_sin_colada_198"
  ],
  [
    "base.automation",
    243,
    "automation_ov_albaran_sin_contacto_243"
  ],
  [
    "base.automation",
    166,
    "automation_ov_certificados_aviso_a_luis_166"
  ],
  [
    "base.automation",
    228,
    "automation_ov_ds_asigna_cert_228"
  ],
  [
    "base.automation",
    177,
    "automation_ov_evitar_lotes_sin_uom_177"
  ],
  [
    "base.automation",
    163,
    "automation_ov_actividades_a_linea_albaran_163"
  ],
  [
    "base.automation",
    213,
    "automation_ov_control_pdf_certificados_213"
  ],
  [
    "base.automation",
    185,
    "automation_ov_retorno_solo_se_pueden_validar_si_la_cantidad_facturada_de_compra_es_menor_que_la_entregada_185"
  ],
  [
    "base.automation",
    199,
    "automation_ov_lotes_sc_sin_colada_prohibir_199"
  ],
  [
    "base.automation",
    208,
    "automation_ov_devoluciones_208"
  ],
  [
    "base.automation",
    22,
    "automation_ov_descripcion_en_picking_22"
  ],
  [
    "base.automation",
    203,
    "automation_ov_regenera_movimientos_original_y_destino_203"
  ],
  [
    "base.automation",
    165,
    "automation_ov_certificados_aviso_a_luis_165"
  ],
  [
    "base.automation",
    209,
    "automation_ov_devoluciones_209"
  ],
  [
    "base.automation",
    220,
    "automation_ov_mensaje_facturacion_in_220"
  ],
  [
    "base.automation",
    202,
    "automation_ov_regenera_movimientos_original_y_destino_202"
  ],
  [
    "base.automation",
    224,
    "automation_ov_certificados_obligatorios_recepciones_224"
  ],
  [
    "base.automation",
    210,
    "automation_ov_certificados_obligatorios_recepciones_210"
  ],
  [
    "base.automation",
    206,
    "automation_ov_certificados_obligatorios_recepciones_206"
  ],
  [
    "base.automation",
    212,
    "automation_ov_actualiza_certificados_212"
  ],
  [
    "base.automation",
    207,
    "automation_ov_certificados_obligatorios_recepciones_207"
  ],
  [
    "base.automation",
    232,
    "automation_ov_estado_pick_y_out_232"
  ],
  [
    "base.automation",
    214,
    "automation_ov_mensaje_facturacion_out_214"
  ],
  [
    "base.automation",
    184,
    "automation_ov_retorno_solo_se_pueden_validar_si_la_cantidad_facturada_es_menor_que_la_entregada_184"
  ],
  [
    "base.automation",
    221,
    "automation_ov_cuentas_analiticas_221"
  ],
  [
    "base.automation",
    240,
    "automation_ov_informacion_coladas_no_disponibles_240"
  ],
  [
    "base.automation",
    225,
    "automation_ov_david_responsable_al_confirmar_in_o_cert_ptllo_225"
  ],
  [
    "base.automation",
    112,
    "automation_ov_informacion_coladas_no_disponibles_112"
  ],
  [
    "ir.ui.menu",
    606,
    "menu_asignacion_606"
  ],
  [
    "ir.ui.menu",
    610,
    "menu_asignacion_por_linea_610"
  ],
  [
    "ir.ui.menu",
    609,
    "menu_entregas_madrid_609"
  ],
  [
    "ir.ui.menu",
    607,
    "menu_entregas_madrid_607"
  ],
  [
    "ir.ui.menu",
    627,
    "menu_entregas_puertollano_627"
  ],
  [
    "ir.ui.menu",
    613,
    "menu_certificados_613"
  ],
  [
    "ir.ui.menu",
    631,
    "menu_devoluciones_o_errores_631"
  ],
  [
    "__any_action__",
    1025,
    "action_unknown_1025"
  ]
]

ACTION_MODELS = [
    "ir.actions.server",
    "ir.actions.act_window",
    "ir.actions.report",
    "ir.actions.act_url",
    "ir.actions.client",
]

def _upsert_xmlid(env, model, res_id, name):
    imd = env["ir.model.data"].sudo()
    existing = imd.search([("module","=",MODULE), ("name","=",name)], limit=1)
    vals = {"module": MODULE, "name": name, "model": model, "res_id": res_id, "noupdate": True}
    if existing:
        # keep xml_id stable, update pointer if needed
        if existing.model != model or existing.res_id != res_id:
            existing.write(vals)
    else:
        imd.create(vals)

def post_init_match_stock_actions_ov(cr, registry):
    env = api.Environment(cr, SUPERUSER_ID, {})
    for model, rid, xml in RECORDS:
        if model == "__any_action__":
            # Try to locate action by ID in known action models
            found = False
            for am in ACTION_MODELS:
                rec = env[am].sudo().browse(rid).exists()
                if rec:
                    _upsert_xmlid(env, am, rec.id, xml)
                    found = True
                    break
            # If not found, skip silently (keeps install robust)
            continue

        rec = env[model].sudo().browse(rid).exists()
        if rec:
            _upsert_xmlid(env, model, rec.id, xml)
